//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Resource.rc
//
#define IDB_BITMAP_MAIN                 1000
#define IDR_MENU_MAIN                   2000
#define IDD_DIALOGBAR_CONTROL           3000
#define IDD_DIALOGBAR_RAW_FILE_LIST     3001
#define ID_MENU_FILE_LOAD               4000
#define ID_MENU_FILE_SAVE               4001
#define ID_MENU_FILE_SAVE_IMAGE         4001
#define ID_MENU_FILE_EXIT               4002
#define ID_MENU_WINDOW_CONTROL_PANEL    4003
#define ID_MENU_WINDOW_RAW_FILE_LIST_PANEL 20000
#define ID_MENU_IMAGE_USE_HIGHT_CONTRAST_FILTER 20001
#define IDC_COMBO_DIALOGBAR_CONTROL_PALETTE 30000
#define IDC_BUTTON_DIALOGBAR_CONTROL_APPLY_PALETTE 30001
#define IDC_LIST_DIALOGBAR_CONTROL_POINT_LIST 30002
#define IDC_BUTTON_DIALOGBAR_CONTROL_CLEAR_LIST 30003
#define IDC_BUTTON_DIALOGBAR_CONTROL_DELETE_SELECTED 30004
#define IDC_EDIT_DIALOGBAR_CONTROL_EMISSIVITY 30005
#define IDC_BUTTON_DIALOGBAR_CONTROL_APPLY_PARAMETERS 30006
#define IDC_LIST_DIALOGBAR_RAW_FILE_LIST_LIST 30007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        10000
#define _APS_NEXT_COMMAND_VALUE         20002
#define _APS_NEXT_CONTROL_VALUE         30006
#define _APS_NEXT_SYMED_VALUE           40000
#endif
#endif
